Repository Team-Never-Land/ThinkerBell-Android, pull requests merged in 2024-09, with the labels that each got.

#10 🐞 공지 | Pagination 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
Labels: 🐞 BugFix

#11 🔎 공지 검색 캠퍼스 구분 | 생활관, 도서관
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeViewModel.kt
Labels: ✨ Feature

#14 📝 기획, 디자인 수정 사항 반영
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/AlarmFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/contact/ContactsFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/deptUrl/DeptUrlFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeCalendarViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/KeywordManageFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/MyPageFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/search/SearchResultFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/search/SearchResultNoticeViewModel.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_common_notice.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_contacts.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_dept_url.xml
  ThinkerBell/presentation/src/main/res/layout/item_notice.xml
Labels: 📝 Modify

#20 🐞 PlayStore 사전 출시 보고서 | 비정상 종료 및 ANR
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/fcm/MyFirebaseMessagingService.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/splash/StartActivity.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/splash/StartViewModel.kt
  ThinkerBell/presentation/src/main/res/drawable/ic_thinkerbell.xml
Labels: 🐞 BugFix

#21 📚 공지사항 스크롤 범위 수정
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/AlarmService.kt
  ThinkerBell/presentation/build.gradle.kts
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_common_notice.xml
Labels: 📝 Modify

#22 ⚙️ 설정 페이지 & DataLayer Refactor
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/ReportDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/ReportDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/DataSourceModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/RepositoryModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/ServiceModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/model/report/ErrorReportRequest.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/ReportService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/AlarmRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/BookmarkRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/KeywordRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/NoticeRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/ReportRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/UnivRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/UserRepositoryImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/utils/ResponseHandler.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/enums/NoticeType.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/model/notice/AllNotices.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/model/notice/BookmarkNotice.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/repository/ReportRepository.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/bookmark/GetBookmarkNoticeUseCase.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/notice/SearchAllNoticesByCategoryUseCase.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/report/PostErrorReportUseCase.kt
  ThinkerBell/presentation/build.gradle.kts
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/HomeActivity.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeCalendarViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/MyPageFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/adapter/FavoriteNoticeAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonRvAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/search/SearchResultNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/search/adapter/SearchResultNoticeAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/ErrorReportFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/ErrorReportViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordAddFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordDeleteDialog.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordManageFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordManagementAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingKeywordAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingViewModel.kt
  ThinkerBell/presentation/src/main/res/drawable/ic_setting.xml
  ThinkerBell/presentation/src/main/res/drawable/shape_error_report_bg.xml
  ThinkerBell/presentation/src/main/res/drawable/toggle_off.xml
  ThinkerBell/presentation/src/main/res/drawable/toggle_on.xml
  ThinkerBell/presentation/src/main/res/drawable/toggle_selector.xml
  ThinkerBell/presentation/src/main/res/drawable/toggle_thumb.xml
  ThinkerBell/presentation/src/main/res/drawable/toggle_track.xml
  ThinkerBell/presentation/src/main/res/layout/activity_home.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_error_report.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_home.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_keyword_add.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_my_page.xml
  ThinkerBell/presentation/src/main/res/layout/fragment_setting.xml
  ThinkerBell/presentation/src/main/res/layout/item_my_page_keyword.xml
  ThinkerBell/presentation/src/main/res/menu/bottom_navigation_menu.xml
  ThinkerBell/presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, 🔨 Refactor

#24 💡 설정 페이지 | 알림 수신 여부 조회 및 수정 기능
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/AlarmDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/AlarmDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/AlarmService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/AlarmRepositoryImpl.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/repository/AlarmRepository.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/alarm/GetAlarmStatusUseCase.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/alarm/PatchAlarmStatusUseCase.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingViewModel.kt
Labels: ✨ Feature

#26 🔨 키워드 별 알림 뱃지 버그 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/AlarmFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/AlarmNoticeFragment.kt
Labels: 🐞 BugFix

#27 🆙 설정 페이지 | 업데이트 유무 확인 기능
  ThinkerBell/gradle/libs.versions.toml
  ThinkerBell/presentation/build.gradle.kts
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/SettingFragment.kt
Labels: ✨ Feature

#29 💬 POST_NOTIFICATIONS 권한 요청
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeFragment.kt
Labels: ✨ Feature

#37 🐞 부서별 연락처 | 클립보드 복사 완료 토스트 보이지 않는 문제
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/AlarmDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/ReportDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/ReportRepositoryImpl.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/contact/ContactDialog.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteScheduleFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteScheduleViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/adapter/FavoriteScheduleAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/KeywordViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/splash/StartActivity.kt
Labels: 🐞 BugFix

#38 🐞 QA 반영 | 검색어 유지, 뷰 겹치는 문제 수정, 오류 신고 SoftKeyboard hide 기능 추가
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/ErrorReportFragment.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_error_report.xml
Labels: 🐞 BugFix, ✨ Feature

#39 🎨 공지 | Campus Filter Dropdown Item Size 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CampusSpinnerAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/notice/CommonNoticeFragment.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_common_notice.xml
  ThinkerBell/presentation/src/main/res/layout/item_spinner_campus_dropdown.xml
  ThinkerBell/presentation/src/main/res/values/themes.xml
Labels: 📝 Modify

#40 🫡 Add Navigate To Home From Dept
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/HomeActivity.kt
Labels: ✨ Feature

#41 홈 화면 캘린더 연도 전환 구현
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/UnivDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/UnivDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/UnivService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/UnivRepositoryImpl.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/repository/UnivRepository.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/univ/GetAcademicScheduleUseCase.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeCalendarFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/HomeCalendarViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/adapter/CalendarMonthAdapter.kt
Labels: ✨ Feature
