Repository Team-Never-Land/ThinkerBell-Android, pull requests merged in 2024-10, with the labels that each got.

#43 즐겨찾기한 학사일정 연도 전환 버튼 버그 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteScheduleFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/adapter/MyPageFavoriteScheduleAdapter.kt
Labels: 🐞 BugFix

#44 🔨 즐겨찾기한 학사일정 연도 순서 버그 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/FavoriteScheduleFragment.kt
Labels: 🐞 BugFix

#46 🫡 오류 신고 | 버튼 비활성 기능 제거 및 Hint 수정
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/ErrorReportFragment.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_error_report.xml
Labels: 📝 Modify

#47 🛠️ 강제 업데이트 기능
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/VersionDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/VersionDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/DataSourceModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/RepositoryModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/ServiceModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/model/ForceUpdateMinVersionResponse.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/VersionService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/VersionRepositoryImpl.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/repository/VersionRepository.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/usecase/version/GetForceUpdateMinVersionUseCase.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/ForceUpdateDialog.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/splash/StartActivity.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/splash/StartViewModel.kt
  ThinkerBell/presentation/src/main/res/layout/dialog_force_update.xml
Labels: ✨ Feature

#51 Fix/alarm page bookmark bugfix
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/AlarmService.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/AlarmNoticeViewModel.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/MyPageFragment.kt
  ThinkerBell/presentation/src/main/res/layout/fragment_my_page.xml
Labels: 🐞 BugFix

#52 🐞 공지 검색 속도 개선을 위한 API 수정 반영
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/NoticeDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/NoticeDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/NoticeService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/NoticeRepositoryImpl.kt
Labels: 🐞 BugFix

#54 💬 푸쉬 알림 | 아이콘 추가
  ThinkerBell/presentation/src/main/AndroidManifest.xml
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/fcm/MyFirebaseMessagingService.kt
  ThinkerBell/presentation/src/main/res/drawable-hdpi/ic_notification_thinkerbell.png
  ThinkerBell/presentation/src/main/res/drawable-mdpi/ic_notification_thinkerbell.png
  ThinkerBell/presentation/src/main/res/drawable-xhdpi/ic_notification_thinkerbell.png
  ThinkerBell/presentation/src/main/res/drawable-xxhdpi/ic_notification_thinkerbell.png
  ThinkerBell/presentation/src/main/res/drawable-xxxhdpi/ic_notification_thinkerbell.png
Labels: ✨ Feature

#56 알림 공지사항 데이터 DTO nullSafe 처리
  ThinkerBell/data/src/main/java/com/neverland/data/remote/model/alarm/AlarmDTO.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/AlarmRepositoryImpl.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/model/alarm/Alarm.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/AlarmNoticeFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/alarm/adapter/AlarmNoticeAdapter.kt
Labels: 🐞 BugFix

#57 즐겨찾기한 학사일정 연도 전환 시 즐겨찾기 해제 버그 수정
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/NoticeDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasource/VersionDataSource.kt
  ThinkerBell/data/src/main/java/com/neverland/data/datasourceImpl/VersionDataSourceImpl.kt
  ThinkerBell/data/src/main/java/com/neverland/data/di/ServiceModule.kt
  ThinkerBell/data/src/main/java/com/neverland/data/remote/service/NoticeService.kt
  ThinkerBell/data/src/main/java/com/neverland/data/repository/VersionRepositoryImpl.kt
  ThinkerBell/domain/src/main/java/com/neverland/domain/repository/VersionRepository.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/home/ForceUpdateDialog.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/MyPageFragment.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/myPage/adapter/FavoriteScheduleAdapter.kt
  ThinkerBell/presentation/src/main/java/com/neverland/thinkerbell/view/setting/ErrorReportFragment.kt
  ThinkerBell/presentation/src/main/res/layout/dialog_force_update.xml
Labels: 🐞 BugFix
